name: tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - run: make install
      - name: Installing dependencies

      - run: npx eslint .
      - name: Runnning eslint

      - run: make test
      - name: Running automated tests

      - uses: paambaati/codeclimate-action@v5.0.0
      - name: Test & publish code coverage

        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
